services:
  - type: web
    name: laravel-inventory
    runtime: docker
    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-inventory.onrender.com
      - key: PORT
        value: 80

      # Configuración de base de datos PostgreSQL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d11nhpbipnbc73d2j8vg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: inventory_db_8afc
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: RGjVqDG3NGDRaiAzF9MRTGrynu1HJzeP
